# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tacticalmelonfarmer/Desktop/ideas/events

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tacticalmelonfarmer/Desktop/ideas/events

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tacticalmelonfarmer/Desktop/ideas/events/CMakeFiles /home/tacticalmelonfarmer/Desktop/ideas/events/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tacticalmelonfarmer/Desktop/ideas/events/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test2

# Build rule for target.
test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test2
.PHONY : test2

# fast build rule for target.
test2/fast:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/build
.PHONY : test2/fast

#=============================================================================
# Target rules for targets named test3

# Build rule for target.
test3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test3
.PHONY : test3

# fast build rule for target.
test3/fast:
	$(MAKE) -f CMakeFiles/test3.dir/build.make CMakeFiles/test3.dir/build
.PHONY : test3/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

#=============================================================================
# Target rules for targets named test4

# Build rule for target.
test4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test4
.PHONY : test4

# fast build rule for target.
test4/fast:
	$(MAKE) -f CMakeFiles/test4.dir/build.make CMakeFiles/test4.dir/build
.PHONY : test4/fast

#=============================================================================
# Target rules for targets named test5

# Build rule for target.
test5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test5
.PHONY : test5

# fast build rule for target.
test5/fast:
	$(MAKE) -f CMakeFiles/test5.dir/build.make CMakeFiles/test5.dir/build
.PHONY : test5/fast

test1.o: test1.cpp.o

.PHONY : test1.o

# target to build an object file
test1.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.o
.PHONY : test1.cpp.o

test1.i: test1.cpp.i

.PHONY : test1.i

# target to preprocess a source file
test1.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.i
.PHONY : test1.cpp.i

test1.s: test1.cpp.s

.PHONY : test1.s

# target to generate assembly for a file
test1.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.s
.PHONY : test1.cpp.s

test2.o: test2.cpp.o

.PHONY : test2.o

# target to build an object file
test2.cpp.o:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.o
.PHONY : test2.cpp.o

test2.i: test2.cpp.i

.PHONY : test2.i

# target to preprocess a source file
test2.cpp.i:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.i
.PHONY : test2.cpp.i

test2.s: test2.cpp.s

.PHONY : test2.s

# target to generate assembly for a file
test2.cpp.s:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.s
.PHONY : test2.cpp.s

test3.o: test3.cpp.o

.PHONY : test3.o

# target to build an object file
test3.cpp.o:
	$(MAKE) -f CMakeFiles/test3.dir/build.make CMakeFiles/test3.dir/test3.cpp.o
.PHONY : test3.cpp.o

test3.i: test3.cpp.i

.PHONY : test3.i

# target to preprocess a source file
test3.cpp.i:
	$(MAKE) -f CMakeFiles/test3.dir/build.make CMakeFiles/test3.dir/test3.cpp.i
.PHONY : test3.cpp.i

test3.s: test3.cpp.s

.PHONY : test3.s

# target to generate assembly for a file
test3.cpp.s:
	$(MAKE) -f CMakeFiles/test3.dir/build.make CMakeFiles/test3.dir/test3.cpp.s
.PHONY : test3.cpp.s

test4.o: test4.cpp.o

.PHONY : test4.o

# target to build an object file
test4.cpp.o:
	$(MAKE) -f CMakeFiles/test4.dir/build.make CMakeFiles/test4.dir/test4.cpp.o
.PHONY : test4.cpp.o

test4.i: test4.cpp.i

.PHONY : test4.i

# target to preprocess a source file
test4.cpp.i:
	$(MAKE) -f CMakeFiles/test4.dir/build.make CMakeFiles/test4.dir/test4.cpp.i
.PHONY : test4.cpp.i

test4.s: test4.cpp.s

.PHONY : test4.s

# target to generate assembly for a file
test4.cpp.s:
	$(MAKE) -f CMakeFiles/test4.dir/build.make CMakeFiles/test4.dir/test4.cpp.s
.PHONY : test4.cpp.s

test5.o: test5.cpp.o

.PHONY : test5.o

# target to build an object file
test5.cpp.o:
	$(MAKE) -f CMakeFiles/test5.dir/build.make CMakeFiles/test5.dir/test5.cpp.o
.PHONY : test5.cpp.o

test5.i: test5.cpp.i

.PHONY : test5.i

# target to preprocess a source file
test5.cpp.i:
	$(MAKE) -f CMakeFiles/test5.dir/build.make CMakeFiles/test5.dir/test5.cpp.i
.PHONY : test5.cpp.i

test5.s: test5.cpp.s

.PHONY : test5.s

# target to generate assembly for a file
test5.cpp.s:
	$(MAKE) -f CMakeFiles/test5.dir/build.make CMakeFiles/test5.dir/test5.cpp.s
.PHONY : test5.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test2"
	@echo "... rebuild_cache"
	@echo "... test3"
	@echo "... test1"
	@echo "... test4"
	@echo "... edit_cache"
	@echo "... test5"
	@echo "... test1.o"
	@echo "... test1.i"
	@echo "... test1.s"
	@echo "... test2.o"
	@echo "... test2.i"
	@echo "... test2.s"
	@echo "... test3.o"
	@echo "... test3.i"
	@echo "... test3.s"
	@echo "... test4.o"
	@echo "... test4.i"
	@echo "... test4.s"
	@echo "... test5.o"
	@echo "... test5.i"
	@echo "... test5.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

